thefactory/marathon-python

marathon/models/app.py, marathon/models/base.py
* `parameters` is now an array, to avoid JSON validation errors it's better to rely on the minimal JSON format (not sure how to send an array for 0.8.0 and a dict for < 0.8.0)
* added `labels`, `max_launch_delay_seconds`, and `maximum_over_capacity` attributes
=> Small changes to fix compatibility issues with Marathon 0.8.0

marathon/client.py
Prior to this change setting the value of some keys of an application
(like 'health_checks' or 'constraints') from a collection that contains objects
to an empty collection and then calling `MarathonClient.update_app` to update the
application resulted in health checks or constraints never being updated.
The cause of this was that `MarathonClient.update_app` always called
`app.to_json(minmal=True)` which kicks out all empty collections.
This change lets the developer choose whether `minimal` should be `True` or `False`.
It retains the original behaviour through a default.
=> Possibility to send the full object to Marathon on update

marathon/models/container.py
I just added **kwargs to `MarathonDockerContainer` constructor so it does not fail when it gets unknown keyword arguments.
=> Quick fix #29 - add kwargs to MarathonDockerContainer.__init__

marathon/models/container.py
This is a new parameter for the upcoming 8.2 release added here:
https://github.com/mesosphere/marathon/commit/2a657006965c13585b1ebca939ce0ed2cb21b21a
This is my first time in this code base. I think I'm doing it right?
=> Added forcePullImage parameter for the container model

marathon/models/app.py
This builds on #35 to fix #34 but also adds forward compatibility for future and yet unknown arguments.
=> adds ignore_http1xx and forward compat kwargs to MarathonHealthCheck

marathon/models/app.py, marathon/models/base.py, marathon/models/group.py
Marathon has a strict requirement for what it allows as app/group ids, so let's enforce this in our client models so we can catch validation errors before attempting to upload.
```python
>>> from marathon.models import MarathonApp
>>> MarathonApp(id='foo')
MarathonApp::foo
>>> MarathonApp(id='foo_bar')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "marathon/models/app.py", line 103, in __init__
self.id = assert_valid_path(id)
File "marathon/models/base.py", line 72, in assert_valid_path
raise ValueError('invalid path (allowed: lowercase letters, digits, hyphen, "/", ".", ".."): %r' % path)
ValueError: invalid path (allowed: lowercase letters, digits, hyphen, "/", ".", ".."): 'foo_bar'
>>> MarathonApp(id='foo_bar/fdas')
Traceback (most recent call last):
File …
```
=> Add validation to marathon app/group ids

itests/docker-compose.yml, itests/environment.py, itests/itest_utils.py, itests/marathon_python.feature, itests/steps/marathon_steps.py, tox.ini
Often when working with upgrades and stuff, we see breaking changes with the python bindings as the API changes.
That is fine, but now do we *know* what to add or when a version bump will be incompatible?
At Yelp we use docker-compose and behave to do our testing, I would like to transplant some of the infrastructure into here so everyone can see together when things break, and how.
If accepted, I'll do a second pass add travis integration, bump the version of marathon we are testing against, and then add more tests besides the trivial one.
(the most recent breakage was having the python bindings list an app that had fancy healthchecks, so I would add a test for that)
cc @ConnorDoyle @mrtyler @evankrall
Here is what the output looks like:
```
tox -e marathon_integration -r
GLOB …
```
=> First pass at adding an itest framework

.travis.yml, itests/steps/marathon_steps.py, marathon/util.py
This caused issues for us described in #50.
This fix makes the json decoder assume that `str` and `unicode` objects should both be treated "as strings"
cc @kevinschoon 
cc @evankrall @mrtyler
=> Added failing test and fix for unicode handling

marathon/models/base.py, marathon/models/deployment.py, tests/test_api.py
the test that I submitted in #53 wasn't actually asserting anything - just that it didn't blow up like it did before. This makes sure that we're actually checking equality of the objects returned.
=> implement __eq__ on base models + fix tests to be useful

marathon/__init__.py
It's rude to interfere with the using application logging configuration...
See [this](http://pythonsweetness.tumblr.com/post/67394619015/use-of-logging-package-from-within-a-library) about "explicitly configuring handlers", which is what `basicConfig` does.
The effect in my application is that it adds a handler to my already existing handlers, causing duplicate output to the console in a way I cannot control.
=> Remove call to logging.basicConfig

marathon/client.py, tests/test_api.py
This ensures that the same endpoint is used irrespective of whether an app_id is passed to list_tasks or not.
=> use the /v2/tasks endpoint for list_tasks

CHANGELOG.md, Makefile
@mbabineau I was preparing for another release and was about to edit the changelog and though "this should be automated".
Mind if we start using https://github.com/skywinder/github-changelog-generator to automake the changelog?
The main thing I was *actually* looking for was those `compare` links that let you show the commits between releases
=> Use automatic changelog generation

marathon/_compat.py, marathon/client.py, marathon/util.py
Fixes bug introduced with ae6763af1f91f2d35aa3ff238c77500dfb6caab0
Also cleans up a few lint issues and unused imports
`unicode` yields a `NameError` in py3.
=> Provide proper compatability support for str/unicode in py3

itests/Dockerfile, itests/marathon_python.feature, itests/steps/marathon_steps.py, marathon/client.py
It looks like these python bindings can't `kill_task` properly on Marathon 11, but they can on Marathon 8.
This is a WIP to add a failing test to catch this, and then hopefully add a fix.
cc @Rob-Johnson  @EvanKrall
=> Added tests for killing tasks on an app

CHANGELOG.md, README.md, setup.py
This is me releasing a new version and documenting in the readme which versions of Marathon are supported, etc. If ship it I'll also tag and release to pypi. (and maybe I'll setup automatic pypi promotion?)
=> Release 0.7.5 for official Marathon 11 support

itests/marathon_apps.feature, itests/marathon_tasks.feature, itests/steps/marathon_steps.py, marathon/client.py
Implement this:
https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-tasks-delete
In fact, as function name `kill_task` and `kill_tasks` both occupied, I'm not sure how to name it.
=> Use the /v2/tasks/delete endpoint for taskkill

itests/marathon_tasks.feature, itests/steps/marathon_steps.py, marathon/client.py
I want to write code like `client.list_tasks("my-test-app")` to get task list, but by now i get an empty list
=> Modify list_apps so user can input app_id without the starting slash

marathon/util.py
=> Don't drop 0s when transforming to JSON

itests/itest_utils.py, itests/steps/marathon_steps.py, marathon/client.py, marathon/exceptions.py, marathon/models/app.py, marathon/models/base.py, marathon/models/constraint.py, marathon/models/container.py, marathon/models/deployment.py, marathon/models/endpoint.py, marathon/models/events.py, marathon/models/group.py, marathon/models/info.py, marathon/models/queue.py, marathon/models/task.py, marathon/util.py, tests/test_api.py, tox.ini
Primary: @Rob-Johnson 
What could possibly go wrong?
=> Comply with pep8 betterer

itests/itest_utils.py, itests/marathon_tasks.feature, itests/steps/marathon_steps.py, marathon/client.py, marathon/models/events.py, requirements.txt, setup.py, tox.ini
The PR allows to use event stream from Marathon REST API added in v0.9.0
=> Add support for /v2/events stream

itests/marathon_deployments.feature, itests/steps/marathon_steps.py, marathon/models/__init__.py, marathon/models/base.py, marathon/models/deployment.py, tests/test_api.py, tox.ini
Primary: @Rob-Johnson 
My previous PR (https://github.com/thefactory/marathon-python/pull/92) lacked support for the `deployments` endpoint. It wasn't really under test.
This PR adds support for the new and old formats, and adds itests and unit tests for both.
We caught this because our paasta itests interacted with the deployments endpoint and were failing.
This was particularly hard for me because I'm an OOP noob. Special thanks to @mjksmith for pairing with me to get this right.
If shipit I'll merge it in and update the readme/release because deployments support for 1.0 is broken right now.
=> Support the deployments endpoint correctly in marathon 1.1.1

marathon/client.py
This adds an optional `force` option to the kill_given_tasks function.
I left it as optional (`None`) because this is undocumented and not backwards compatible with old versions of marathon.
=> Added force option for kill_given_tasks

marathon/util.py
As the time format that MarathonApp.to_json() and MarathonApp.from_json() used is different, so the json dumped by to_json() can not be loaded by frmo_json().
This commit will use unify time format for both method.
=> Change to_json() datatime format

marathon/client.py, marathon/models/app.py
Fix task_stats  bugs in MarathonApp init that wrongly use version_info.
Add more query parameters to list_apps and get_app to get more info.
Add readiness_check_results to MarathonApp when query embed with app.readiness marathon will return readinessCheckResults field.
=> task_stats bugfix and query improvements.

marathon/client.py
In order to clean up persistent volumes associated with
containers, we need to pass the 'wipe' param to Marathon.
See: https://mesosphere.github.io/marathon/docs/rest-api.html#delete-v2-apps-appid-tasks
=> Add 'wipe' option to kill_task methods

marathon/models/task.py
Good day,
this PR fixes #110.
ip_addresses field is passed via __init__ parameters in MarathonTask, but never set.
=> Issue110: MarathonTask.ip_addresses attribute is set properly

marathon/models/container.py
This is required for supporting persistent local volumes:
https://mesosphere.github.io/marathon/docs/persistent-volumes.html
=> Add 'persistent' volume option

marathon/models/task.py
Seems that on Marathon 0.15.5 the task object when performing a `Marathon_Client().get_app` to the `/v2/apps/{app-id}` endpoint has an extra attribute `state` in the response. Simply adding it to the model rectified the issue for me.
=> Add in state to the task model

marathon/models/app.py
Fetch attribute is missed now and due to marathon document, fetch will take place of uris in version after 0.15.0
=> Set fetch in MarathonApp.

marathon/models/events.py
For TASK_FAILED status_update_event, there is a message field contains reason about why launch task failed. That's much helpful for debugging. However other status_update_events do not contain this field, so I changed the way MarathonEvent init to avoid unnecessary warn log.
=> Add message field for MarathonStatusUpdateEvent.

marathon/exceptions.py, marathon/models/app.py
HTTP errors like 503 do not have a content set by Marathon. Try to use
the response reason string as an alternative error message.
=> Handle HTTP errors without content graceful

marathon/client.py
Right now when Client opens new tcp connection for any call to Marathon api. Use requests.Session provide great performance improvement by ensuring keep-alive connections when many sequential calls are made.
=> Use requests.Session while communicating with Marathon.

marathon/client.py
The Marathon response for a GET /v2/groups/{group_id} call does not have a resource_name in the JSON response.
=> Issue #70: Remove resource_name from get_group

marathon/client.py
The API call GET /v2/apps has a query parameter called id that will let you pass in either the id of an app itself or a portion of the id.  This is quite useful when you only want to list apps in a certain group, and would like them all returned in a flat list instead of the the nested group style that is returned when calling get_group.  Chose app_id as parameter name instead of the query param's name 'id' so as not to shadow the python built-in id function.
=> Expose id query param in list_apps

marathon/models/app.py
.items() works in both.  This dictionary won't ever be especially large,
so the performance hit for not using an iterator in py27 is negligible.
If you really want, I can pull in ```six.iteritems()``` but I didn't see any other uses of ```six``` so I didn't want to introduce a new dependency.
=> Fix py3k regression in 0.8.3

marathon/client.py
Currently the python API only supports updating a single app in one call.  The REST API however, support a PUT call to the /v2/apps path that allows for updating several apps in one go.  This PR exposes this call in the form of an update_apps function which takes in a list of MarathonApp objects.  Taking the possible convenience aside for a moment, my actual motivation for this was performance.  We perform update operations on 10s of applications at a time.  Doing these one by one would take up to a few minutes.  Implementing this has trimmed it down to under 10 seconds.  Hopefully the actual implementation is up to common convention for marathon-python, but have no issue changing whatever and submitting a new PR if something is off and it will help to get this merged. 
Thanks, 
Kevin
=> Add update_apps method to client

marathon/models/app.py
Resolves #140 - `gpus` TypeError
=> Fix #140 - Resolve gpus TypeError

.travis.yml, Makefile, itests/install-marathon.sh, itests/itest.sh, itests/itest_utils.py, requirements.txt, tests/test_api.py, tox.ini
I'm not sure this'll work...but it seems to locally?
Fixes #80.
=> run tox against multiple python versions

marathon/client.py
DCOS has an `adminrouter` to control public access
to the Marathon API.  This requires token-based authentication.
This simple change lets a user pass in an `auth_token` rather
than `username` and `password` for this use-case.
Fixes #148
=> Add support for token-based Auth

marathon/exceptions.py
Hello
When attempting to debug a failure on an update of a group of apps, I noticed that the response object was returning a list of error details in addition to a simple message.  These details turned out to be a list of dictionaries, containing detail on each app that was in error, and all errors associated with that app.  It was of the form
```json
[
{"errors": ["error 1", "error 2"], "path": "/path/to/app1"},
{"errors": ["error 1", "error 2"], "path": "/path/to/app2"}
]
```
Currently the MarathonHttpError object does not expose the details field from the response object.  This pull request adds the details field to the MarathonHttpError object in addition to the higher level message field from the response that is already a part of the MarathonHttpError object.  I could not find any …
=> Expose error details from response object MarathonHttpError

marathon/client.py
In my case, I have a Marathon server with self signed certificates that does not support SSL certificates verification. As requests lib support to disable it, pass the parameter to the requests lib.
=> Allow to disable SSL certificate validation

marathon/models/app.py, marathon/models/group.py, marathon/models/task.py
Looks like we did the same thing to some extend.
I also identified the new `MarathonGroup.pods` and `MarathonHealthCheckResult.instance_id`.
Have not had the need to implement the proper `pod` classes, that's why I put in a ToDo note.
=> Add new Marathon 1.4 API keywords

marathon/models/app.py, tests/test_model_app.py
Hello,
This PR adds a convenient method to manipulate the dict of env vars of an App model. Hope it helps.
I'm currently building an HTTP API that sits in front of Marathon and I'm currently using your project to wrap all calls to Marathon HTTP API.
=> Adds MarathonApp.add_env() method

itests/install-marathon.sh, marathon/models/app.py
Marathon 1.4.0 updated the `KILL_SELECTIONS`: https://github.com/mesosphere/marathon/issues/4882 . We also no longer need the yelp/paasta apt repository.
=> Update to work with Marathon 1.4.0

marathon/models/events.py
As of now, when the event stream gets a  app_terminated_event, it raises an exeption : 
MarathonError: Unknown event_type: app_terminated_event, data: {u'eventType': u'app_terminated_event', u'timestamp': u'2017-02-23T08:54:44.470Z', u'appId': u'/longtest/ms/beds-node'}
This fixs it.
Closes #151.
=> Updated event.py to handle app_terminated_event.

marathon/client.py, tests/test_api.py
In Marathon 1.4.1 `/v2/tasks` endpoint returns empty list, however there is `/v2/apps/<app_id>/tasks` endpoint which seems to be better for this case anyway.
=> Use Marathon /v2/apps/<app_id>/tasks endpoint to get tasks by id.

marathon/models/queue.py
There appears to be a new attribute called `since` that looks like this:
`"since":"2017-03-16T22:37:26.758Z"`
=> Add support for 'since' in /v2/queue

.travis.yml
Fix broken build (see https://github.com/thefactory/marathon-python/issues/180)
=> [fix] broken build: glibc++ not found

.travis.yml, marathon/exceptions.py, tests/test_exceptions.py
- it answers to https://github.com/thefactory/marathon-python/issues/22
- it proposes a different implementation (without catching exceptions) than:
- https://github.com/thefactory/marathon-python/pull/167/commits/9443c7d188b033ad0d5fc01001c9c4e48e658dac
- https://github.com/thefactory/marathon-python/pull/138/commits/7f2999f7c052a196eb74754f997798d899a0c486
- it adds two tests to verify the behavior of the new condition
=> [fix] Handle non-JSON errors from Marathon

marathon/util.py, tests/test_util.py
it was converting "ignore_http1xx" into "ignoreHttp1Xx" instead of
"ignoreHttp1xx" (2 lower x at the end)
fixes issue https://github.com/thefactory/marathon-python/issues/125
=> [fix] util.to_camel_case doesn't handle digits

marathon/client.py
Fix #187 by encoding response in utf-8 before logging it.
It could also be done for the whole logger but I have no idea how right now.
=> handle case when non-ascii char are logged

marathon/models/constraint.py
`MAX_PER` is missing. More will be in the future, I'm sure.
> The client should not enforce what the API accepts as parameter options at the very least.
Ty.
=> Remove out of date constraint validation of operator.

marathon/client.py, marathon/models/constraint.py
This is just a proposal. If you just store events in a message queue and leave it to other consumers, then there is no need to parse the event data as MarathonEvent object
=> Add raw_data option for event_stream method

marathon/models/base.py
For example, if you're trying to compare a MarathonObject with ``None`` or
``str()`` those won't have the ``__dict__`` attribute. Another approach was
to test if the ``__dict__`` attribute was part of ``other`` but it introspection
feels a bit more off than this.
=> There are cases where this check stack traces

marathon/client.py
Hi folks,
I'd suggest adding the param note in the `MarathonClient` initial method as I have been stricken by the `requests.session reusing` issue.
In my environment, my web server calls a lot of times to marathon via `marathon-python`, and I initial the client each call, so it appears thousands of TIME_WAIT connections on the server. Thus, adding the session param hint will help the others clear about that.
Thanks.
=> Add requests session param tip.

marathon/models/base.py, tests/test_model_object.py
Turns out that Python3 does not allow child classes to inherit __hash__ methods, if you explicitly define __eq__ you also have to explicitly define __eq__.
MarathonTask -> MarathonResource -> MarathonObject, so for MarathonTasks to be hashible we actually need to define __hash__ on MarathonResource.
Oops.
=> Fix MarathonResource hash as well

marathon/models/container.py
Hi !
I just added the 'udp,tcp' protocol to the container ones, it is now supported by Marathon. Don't hesitate to ask more !
Fixes #150.
=> Add "udp,tcp" to authorized protocols for containers

marathon/client.py
for https://github.com/Yelp/paasta/issues/1408
=> add embed option for /v2/queue

marathon/client.py
This is the API in marathon: `GET /v2/apps?label={labelSelectorQuery}`
Applications needs to format their queries into `str` since it's difficult to compose the query string from `marathon-python` point of view. 
Thanks for reviewing.
=> Support filtering applications by labels

.travis.yml, marathon/models/container.py
The Marathon v1.5 release (coming in DCOS 1.10) includes breaking changes that cause the Python API to fail on `/v2/apps` requests. This patch is backwards compatible for Marathon versions prior to 1.5.
Ref: https://jira.mesosphere.com/browse/MARATHON-7026
A release along with this change would be appreciated, so that PyPI will contain the resolution.
=> Fix for Marathon 1.5 breaking the /v2/apps API moving portMappings

marathon/models/container.py
Remove container.docker.network default value to allow using MESOS container engine and .networks on newer versions of marathon
See issue #186
=> Remove default container.docker.network

marathon/models/base.py, marathon/models/group.py, tests/test_model_group.py
This validation was preventig the use of the root group (`/`), both from
`MarathonGroup().from_json(<data>)` and `MarathonClient().get_group("/")`
Fixes issue #227
=> Removes id validation from MarathonGroup()

marathon/__init__.py, marathon/models/app.py, marathon/util.py
#222
The current version of marathon-python (0.9.2) generates COMMAND type protocol healthchecks command property as a string, but current version of marathon expects an object with the 'value' property:
Current:
```json
{
"protocol": "COMMAND",
"command":  "curl -f -X GET http://$HOST:$PORT0/health"
}
```
Expected:
```json
{
"protocol": "COMMAND",
"command": { "value": "curl -f -X GET http://$HOST:$PORT0/health" }
}
```
I can see that all the messages in the package are handled by the logger defined in the `marathon/__init__.py`, so instead of using the `warnings` package to issue a `DeprecationWarning` I would rather user `marathon.log.warn()` to be in accordance with the rest of the package.
I don't wanna do  a `import  marathon` because I'd be importing many things I don't need into …
=> Fix health check 'command' 

itests/install-marathon.sh
oracle-java7-installer is not present on recent travis vms.
Fixes #249
=> install-marathon.sh: do not remove oracle-java7-installer

marathon/models/events.py, tests/test_model_event.py
Found in https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/core/event/Events.scala
=> events: add a few attributes

marathon/client.py
Some of our marathon applications requires an empty port configuration on create. We do it by setting the `portsMapping` to `null`, but that value is ignored by `create_app` because we don't have control on `minimal` parameter when serializing app configuration.
=> Possibility for send the full json object on create

marathon/models/task.py
Missing region and zone members resulted in stack trace when making calls
to `client.get_app` under DCOS EE 1.11+. I've resolved the problem with addition of both kwargs to `MarathonTask`. It was unclear to me how I could adequately test this with the behave tests. The main problem I had was in identifying how to enable the Marathon region and zone values in the open-source releases. I'm happy to provide test coverage if you can provide a pointer to how I'd accomplish this. Regardless, I've tested to ensure this resolves my individual problem.
Stack trace snippet experienced when using `marathon` package against DCOS EE 1.11.8 cluster deployed in AWS:
```
File "/usr/lib/python2.7/site-packages/marathon/client.py", line 252, in get_app
return self._parse_response(response, MarathonApp, …
```
=> Added region and zone members to task model.

marathon/client.py
Currently it always returns `false`, even on a `200 OK` response.
=> Fix return value for kill_given_tasks.

.travis.yml, Makefile, README.md, itests/.dockerignore, itests/Dockerfile, itests/docker-compose.yml, itests/install-marathon.sh, itests/itest.sh, itests/start-marathon.sh
These changes work locally, I've not tested TravisCI yet.
If you are ok with using pre-built container images, I'd change the tests to build everytime and just pull the images from https://hub.docker.com/r/missingcharacter/marathon-python/tags
It might be a good idea for you guys to create your own repository in hub.docker.com for the images to be pulled from.
=> Moving marathon away from ubuntu and starting from mesosphere dockerhub
