thefactory/marathon-python

marathon/util.py
Fixing issue #26 
Changed hasattr(obj, 'iteritems') to try/except getting rid of lib use_2to3 failed to fix the python version conflict.
=> Fixed #26:Using try/except to get rid of use_2to3 failing

marathon/models/container.py
Should be pretty self explanatory, but #31 wasn't enough to make it work.
=> Make `force_pull_image` actually work

marathon/models/endpoint.py
Docstring values aren't consistent with the actual class.  Fixed task_id.
=> Update endpoint docstring.

marathon/models/deployment.py, requirements.txt, tests/test_api.py, tox.ini
fixes parsing of deployments endpoint. duplicate of #40
=> Fix deployments parsing

Makefile, setup.cfg, setup.py
=> Add support for building with a wheel and cleanup setup.py

itests/steps/marathon_steps.py, marathon/models/container.py
=> Change MarathonDockerContainer.parameters to type list

marathon/client.py, marathon/models/app.py, marathon/models/queue.py
These are needed to do similar app status checks as described in:
https://mesosphere.github.io/marathon/docs/marathon-ui.html#application-status-reference
=> update for v2/queue and v2/apps?embed=apps.taskStats

itests/steps/marathon_steps.py, marathon/models/container.py
=> add name attribute to port mapping

marathon/client.py
=> Make exception handling work with py3k

marathon/models/app.py
Good day, this one adds type assertion for readiness_checks as it is done for health checks and other fields
=> Type assertion for ReadinessCheck in MarathonApp.__init__ method added

.travis.yml
=> Try to fix java hostname issues

marathon/client.py
This allows programs using this library to set a user-agent for all requests, set custom headers etc
=> Allow setting of a custom requests session

marathon/models/container.py
=> Add external volume support

marathon/models/container.py
=> Mesos container support

marathon/models/app.py
Adding more things to support the new Marathon 1.4 API early so we can test for https://github.com/mesosphere/marathon/issues/3783
=> Added more unimplemented Marathon 1.4 API keywords

setup.py
This was by bad. I should had removed this right after my last PR.
=> Removed unused sseclient depencency

itests/Dockerfile, marathon/models/app.py
These are some new (undocumented) API features for the upcoming marathon 1.4 release.
=> Marathon 1.4 instance

docs/index.rst
Change the location of the rest-api.md
https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api.md
=> Change location

marathon/models/queue.py
/v2/queue also added a processed_offers_summary attribute
=> Support processed_offers_summary attribute

marathon/models/app.py
=> Adding the key "networks" in the JSON received of marathon

marathon/models/deployment.py, marathon/models/events.py
Updated for https://github.com/mesosphere/marathon/blob/v1.4.2/src/main/scala/mesosphere/marathon/core/event/Events.scala
closes #196 and #191
=> add new marathon event_stream events

marathon/models/base.py, tests/test_model_object.py
This should fix #203 in the short term
=> Add hash to marathon object

marathon/client.py, setup.py
With TCP keepalive client can get exception if server fail silently
or network partition.
=> Enable TCP keepalive for sse requests

marathon/models/app.py, tests/test_model_app.py
Yelp internal - PAASTA-11697
https://jira.mesosphere.com/browse/MARATHON-7518
=> support more datetime formats in MarathonAppVersionInfo

marathon/models/queue.py
=> Fix MarathonQueueItem to know about the possible last_unused_offers arg

marathon/client.py
=> fix isuuse-238

marathon/client.py
=> MarathonClient: set verify when using sse_session

marathon/models/group.py, tests/test_model_group.py
This was introduced in Marathon v1.9.32
Fixes #280
=> Add attribute enforce_role to groups.
